markdown: redcarpet
name: Voice and tone
exclude:
- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- go
- vendor

permalink: pretty
highlighter: rouge
incremental: true

sass:
  style: :compressed

# Author/Organization info to be displayed in the templates
author:
  name: 18F
  url: https://18f.gsa.gov

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /assets/img/18f-logo.png
logoalt: 18F logo

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Introduction
  internal: true
- text: What's the difference between voice and tone
  url: whats-the-difference/
  internal: true
- text: Our voice
  url: our-voice/
  internal: true
- text: Establishing your own voice
  url: establishing-your-own-voice/
  internal: true
- text: Choosing a tone
  url: choosing-a-tone/
  internal: true
- text: Test your knowledge!
  url: test-your-knowledge/
  internal: true
  children:
  - text: Activity one
    url: activity-1/
    internal: true
  - text: Activity two
    url: activity-2/
    internal: true
  - text: Activity three
    url: activity-3/
    internal: true
- text: Additional resources
  url: additional-resources/
  internal: true

repos:
- name: edu-voice-and-tone
  description: Main repository
  url: https://github.com/18F/edu-voice-and-tone

back_link:
  url: "https://pages.18f.gov/edu/"
  text: Return to 18F Edu

google_analytics_ua: UA-48605964-19

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
- scope:
    path: ""
  values:
    layout: "guides_style_18f_default"
